version: "3"
services:
    maven:
        build:
            context: maven/
        volumes: 
            - type: volume
              source: data
              target: /home/war
    tomcat:
        image: tomcat:slim
        volumes: 
            - type: volume
              source: data
              target: /usr/local/tomcat/webapps
        ports: 
            - "8080:8080"
        depends_on: 
            - maven

volumes: 
    data: